-- MySQL Script generated by MySQL Workbench
-- 2018年04月27日 星期五 15时31分11秒
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema T3Robot
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `T3Robot` ;

-- -----------------------------------------------------
-- Schema T3Robot
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `T3Robot` DEFAULT CHARACTER SET utf8 ;
USE `T3Robot` ;

-- -----------------------------------------------------
-- Table `T3Robot`.`T3Pose`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `T3Robot`.`T3Pose` ;

CREATE TABLE IF NOT EXISTS `T3Robot`.`T3Pose` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `x` DOUBLE NOT NULL,
  `y` DOUBLE NOT NULL,
  `z` DOUBLE NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '地点表';


-- -----------------------------------------------------
-- Table `T3Robot`.`T3Position`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `T3Robot`.`T3Position` ;

CREATE TABLE IF NOT EXISTS `T3Robot`.`T3Position` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `T3PoseId` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_T3Position_1_idx` (`T3PoseId` ASC),
  CONSTRAINT `fk_T3Position_1`
    FOREIGN KEY (`T3PoseId`)
    REFERENCES `T3Robot`.`T3Pose` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '位置信息列表';


-- -----------------------------------------------------
-- Table `T3Robot`.`T3UserInfo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `T3Robot`.`T3UserInfo` ;

CREATE TABLE IF NOT EXISTS `T3Robot`.`T3UserInfo` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NULL,
  `Pwd` VARCHAR(45) NULL,
  `Gender` INT NULL,
  `Age` INT NULL,
  `Ip` VARCHAR(45) NULL,
  `Feature` BLOB NULL,
  `Type` INT NOT NULL,
  `Position` INT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_T3UserInfo_1_idx` (`Position` ASC),
  CONSTRAINT `fk_T3UserInfo_1`
    FOREIGN KEY (`Position`)
    REFERENCES `T3Robot`.`T3Position` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '用户信息列表';


-- -----------------------------------------------------
-- Table `T3Robot`.`T3HardwareState`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `T3Robot`.`T3HardwareState` ;

CREATE TABLE IF NOT EXISTS `T3Robot`.`T3HardwareState` (
  `Id` INT NOT NULL,
  `sweeperTime` INT NULL,
  `AerialDetectLevel` INT NULL,
  `BatterChargeState` INT NULL,
  `SmokeTransducer1` INT NULL,
  `SmokeTransducer3` INT NULL,
  `SmokeTransducer2` INT NULL,
  `SteeringPlatformat1` INT NULL,
  `SteeringPlatformat2` INT NULL,
  `ExpressDoorState` INT NULL,
  `ExpressDoorLocked` INT NULL,
  `ElectronicLock1` INT NULL,
  `ElectronicLock2` INT NULL,
  `SweeperLocked1` INT NULL,
  `SweeperLocked2` INT NULL,
  `SweeperState` INT NULL,
  `DustBoxBeFull` INT NULL,
  `AerialDetectLocked` INT NULL,
  `HumidifierState` INT NULL,
  `LiquidLevelDetect1` INT NULL,
  `LiquidLevelDetect2` INT NULL,
  `AirCleanerState` INT NULL,
  `ProjectorState` INT NULL,
  `PrinterState` INT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '机器人硬件状态量';


-- -----------------------------------------------------
-- Table `T3Robot`.`T3Task`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `T3Robot`.`T3Task` ;

CREATE TABLE IF NOT EXISTS `T3Robot`.`T3Task` (
  `Id` VARCHAR(45) NOT NULL,
  `Type` INT NULL,
  `Sender` INT NULL,
  `Priority` INT NULL,
  `State` INT NULL,
  `taskId` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`taskId`, `Id`),
  INDEX `fk_T3Task_1_idx` (`Sender` ASC),
  CONSTRAINT `fk_T3Task_1`
    FOREIGN KEY (`Sender`)
    REFERENCES `T3Robot`.`T3UserInfo` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '任务列表';


-- -----------------------------------------------------
-- Table `T3Robot`.`T3NavigationTask`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `T3Robot`.`T3NavigationTask` ;

CREATE TABLE IF NOT EXISTS `T3Robot`.`T3NavigationTask` (
  `Id` VARCHAR(45) NOT NULL,
  `Route` BLOB NULL,
  `DestinationId` INT NULL,
  `State` INT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_T3NavigationTask_2_idx` (`DestinationId` ASC),
  CONSTRAINT `fk_T3NavigationTask_2`
    FOREIGN KEY (`DestinationId`)
    REFERENCES `T3Robot`.`T3Pose` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `T3Robot`.`T3ExpressTask`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `T3Robot`.`T3ExpressTask` ;

CREATE TABLE IF NOT EXISTS `T3Robot`.`T3ExpressTask` (
  `Id` VARCHAR(45) NOT NULL,
  `Sender` INT NULL,
  `Recipient` INT NULL,
  `ExpressGoods` VARCHAR(45) NULL,
  `ExpressBoxNum` INT NULL,
  `State` INT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_T3ExpressTask_2_idx` (`Sender` ASC),
  INDEX `fk_T3ExpressTask_3_idx` (`Recipient` ASC),
  CONSTRAINT `fk_T3ExpressTask_2`
    FOREIGN KEY (`Sender`)
    REFERENCES `T3Robot`.`T3UserInfo` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_T3ExpressTask_3`
    FOREIGN KEY (`Recipient`)
    REFERENCES `T3Robot`.`T3UserInfo` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `T3Robot`.`T3Attendence`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `T3Robot`.`T3Attendence` ;

CREATE TABLE IF NOT EXISTS `T3Robot`.`T3Attendence` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `UserInfoId` INT NULL,
  `Time` DATETIME NULL,
  `State` INT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_T3Attendence_1_idx` (`UserInfoId` ASC),
  CONSTRAINT `fk_T3Attendence_1`
    FOREIGN KEY (`UserInfoId`)
    REFERENCES `T3Robot`.`T3UserInfo` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `T3Robot`.`T3HardwareTask`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `T3Robot`.`T3HardwareTask` ;

CREATE TABLE IF NOT EXISTS `T3Robot`.`T3HardwareTask` (
  `Id` VARCHAR(45) NOT NULL,
  `HardwareType` INT NOT NULL,
  `state` INT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `T3Robot`.`T3InterviewTask`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `T3Robot`.`T3InterviewTask` ;

CREATE TABLE IF NOT EXISTS `T3Robot`.`T3InterviewTask` (
  `Id` VARCHAR(45) NOT NULL,
  `Position` INT NOT NULL,
  `MeetingRoom` INT NULL,
  `Time` DATETIME NULL,
  `Interviewer` INT NULL,
  `State` INT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_T3InterviewTask_2_idx` (`Interviewer` ASC),
  CONSTRAINT `fk_T3InterviewTask_2`
    FOREIGN KEY (`Interviewer`)
    REFERENCES `T3Robot`.`T3UserInfo` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `T3Robot`.`T3RobotState`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `T3Robot`.`T3RobotState` ;

CREATE TABLE IF NOT EXISTS `T3Robot`.`T3RobotState` (
  `Id` INT NOT NULL,
  `NowPose` INT NULL,
  `Velocity` FLOAT NULL,
  `BatteryLife` INT NULL,
  `Ip` VARCHAR(45) NULL,
  `ChargePoint` INT NULL,
  `OriginPoint` INT NULL,
  `State` INT NULL,
  `robotId` INT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_T3RobotState_2_idx` (`OriginPoint` ASC),
  INDEX `fk_T3RobotState_4_idx` (`NowPose` ASC),
  INDEX `fk_T3RobotState_3_idx` (`robotId` ASC),
  CONSTRAINT `fk_T3RobotState_1`
    FOREIGN KEY (`NowPose`)
    REFERENCES `T3Robot`.`T3Position` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_T3RobotState_2`
    FOREIGN KEY (`OriginPoint`)
    REFERENCES `T3Robot`.`T3Position` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_T3RobotState_3`
    FOREIGN KEY (`robotId`)
    REFERENCES `T3Robot`.`T3UserInfo` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_T3RobotState_4`
    FOREIGN KEY (`NowPose`)
    REFERENCES `T3Robot`.`T3Pose` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '机器人状态';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
